yogashala/urls.py
from atexit import register
from re import template
from unicodedata import name
from venv import create
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from yogashala.models import course, profile
from .views import blog_detail, course_detail, course_purchase,courses, email,home,blogs,about,esewapayment,course_purchase,booked,add_cart,findpandit,view_cart,remove_from_cart,create_pandit,course_purchase_cart


urlpatterns = [
    path('',home,name='home'),
    path('courses',courses,name='courses'),
    path('course-detail/<int:pk>',course_detail,name='course_detail'),
    path('blog',blogs,name='blogs'),
    path('blog-detail/<int:pk>',blog_detail,name='blog_detail'),
    path('about/',about,name='about'),
    path('email/',email,name='email'),
    path('esewapayment/',esewapayment,name='esewapayment'),
    path('course_purchase/<int:pk>',course_purchase,name='course_purchase'),
    path('add_cart/<int:pk>',add_cart,name='add_cart'),
    path('course_purchase_cart/',course_purchase_cart, name='course_purchase_cart'),
    path('booked/',booked,name='booked'),
    path('findpandit/<str:name>/',findpandit, name='findpandit'),
    path('view_cart/',view_cart,name='view_cart'),    
    path('remove_from_cart/<int:product_id>/', remove_from_cart, name='remove_from_cart'),
    path('create_pandit/',create_pandit,name='create_pandit'),    
]

yogastudio/urls.py
from xml.dom.minidom import Document
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
# from yogashala import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('yogashala.urls'))
]
urlpatterns=urlpatterns+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

yogashala/models.py
from copyreg import pickle
from pyexpat import model
from sqlite3 import Date
from statistics import mode
from turtle import back
from unicodedata import category
from xmlrpc.client import DateTime
from django.db import models
import uuid  # Import the UUID module
import os
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.conf import settings
from django.template.loader import render_to_string
from django.contrib.auth.models import User
from django.core.mail import EmailMessage
from django.contrib.auth.models import AbstractUser
from django.utils import timezone


# Create your models here.
class course(models.Model):
    id = models.AutoField(primary_key=True)  # Create an AutoField primary key
    course_name=models.CharField(max_length=1000,unique=False,null=False,blank=False)
    file_mainpic=models.FileField(unique=False,blank=False)
    trainer_name=models.ForeignKey('Trainer',on_delete=models.CASCADE,related_name='trainers_profile')
    title=models.TextField(max_length=200,null=False,blank=False)
    Description=models.TextField(null=False,blank=False)
    quotes=models.TextField(null=False,blank=False)
    important_notes=models.TextField(null=False,blank=False)
    price=models.IntegerField(null=False,blank=False)
    pic1=models.FileField(null=False,blank=False)
    pic2=models.FileField(blank=False)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    offers=models.CharField(max_length=500,blank=True,null=True,default='0')
    # offers_date= models.DateField(default=timezone.now, blank=True, null=True)
    offers_date = models.DateField(blank=True, null=True)
    subject_email=models.CharField(blank=True, null=True)
    def __str__(self):
        return self.course_name

    def filename(self):
        return os.path.basename(self.file_mainpic.name)
    

COUNTRY_CHOICES = [
        ('India', 'India'),
        ('Nepal', 'Nepal'),
        ('Canada', 'Canada'),
        ('USA', 'USA'),
        ('Australia', 'Australia'),
    ]   

class Trainer(models.Model):
    id = models.AutoField(primary_key=True)  # Create an AutoField primary key

    trainer_name=models.CharField(max_length=150,null=False,blank=False)
    expertise=models.CharField(max_length=1000,null=False,blank=False)
    trainer_pic=models.FileField(null=False,blank=False)
    country = models.CharField(max_length=100,null=False,blank=False)
    city=models.CharField(max_length=300,null=False,blank=False)
    location=models.CharField(max_length=300,null=False,blank=False)
    contact=models.CharField(max_length=20,null=False,blank=False)
    desc = models.TextField(null=True, blank=True)

    Email=models.EmailField(max_length=150,null=False,blank=False)
    
    is_trainer = models.BooleanField(default=False)
    
    def __str__(self):
        return self.trainer_name



class course_buy(models.Model):
    id = models.AutoField(primary_key=True)  # Create an AutoField primary key
    name = models.CharField(max_length=100,null=False,blank=False)
    country = models.CharField(max_length=100,null=False,blank=False)
    puja_date = models.DateField(null=False,blank=False)
    Email = models.EmailField(null=False,blank=False)
    contact = models.CharField(null=False,blank=False)
    payment = models.CharField(null=False,blank=False)
    address = models.TextField(max_length=500,null=False,blank=False)
    puja_name= models.ForeignKey(course, on_delete=models.CASCADE)
    message=models.TextField(default='')
    paid=models.BooleanField(default=False,choices=[
            (True, 'Yes'),
            (False, 'No')
        ])
    completed=models.BooleanField(default=False,choices=[
            (True, 'Yes'),
            (False, 'No')])
    
class category(models.Model):
    category=models.CharField(max_length=1000)

    def __str__(self):
        return self.category


class blog(models.Model):
    title=models.CharField(max_length=1000,null=False,blank=False)
    top_content=models.TextField(null=False,blank=False)
    username=models.ForeignKey(User,on_delete=models.CASCADE)
    content=models.TextField(null=False,blank=False)
    important_notes=models.TextField()
    category=models.ForeignKey(category,on_delete=models.CASCADE)
    main_pic1=models.FileField(null=False,blank=False)
    pic1=models.FileField(null=False,blank=False)
    pic2=models.FileField(null=False,blank=False)
    Date=models.DateField(null=False,blank=True)

     
    def __str__(self):
        return self.title

class Itemcart(models.Model):
    id = models.AutoField(primary_key=True)  # Create an AutoField primary key
    items = models.ManyToManyField(course, related_name='course')
    purchase_date = models.DateTimeField(default=timezone.now)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)
    is_purchased = models.BooleanField(default=False)
    is_completed = models.BooleanField(default=False)
    name=models.CharField(max_length=200)
    country=models.CharField(max_length=200)
    location=models.CharField(max_length=200)
    Email = models.EmailField(max_length=200)
    contact = models.CharField(max_length=50, null=True, blank=True)
    quantity= models.CharField(max_length=20, null=True, blank=True)
    Any_sepcial_request = models.TextField(null=True, blank=True)

    def __str__(self):
        course_names = ', '.join([str(course) for course in self.items.all()])
        return f"Purchased Courses: {course_names}"




class profile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    nationality=models.CharField(max_length=200,blank=False)
    email = models.EmailField(blank=False,)
    firstname=models.CharField(blank=False,max_length=200)
    lastname=models.CharField(blank=False,max_length=300)
    

    def __str__(self):
        return self.firstname

class email_subscription(models.Model):
    email=models.EmailField(unique=True)


    def __str__(self):
        return self.email


@receiver(post_save,sender=course)
def send_blog_notification(sender,instance,created,**kwargs):
    if created:
        subscribers=email_subscription.objects.all()
        
        email_from = settings.EMAIL_HOST_USER
        
        subject = instance.subject_email

        for subscriber in subscribers:
            recipient_email=subscriber.email
                
            if instance.offers=='0' and instance.subject_email is not None:
                context = {
                'name':instance.course_name,
                'Description':instance.Description,
                # 'Date':instance.offers_date,

                }
                html_version = 'email.html'
                html_message = render_to_string(html_version, {'context': context})
                message = EmailMessage(subject,html_message,email_from,[recipient_email])
                message.content_subtype = 'html'
                message.send()
                
            # else:
            #     context = {
            #  'name':instance.course_name,
            #  'Description':instance.Description,
            #  'offers':instance.offers
             
            #  }
            #     html_version = 'email.html'
            #     html_message = render_to_string(html_version, {'context': context})
            #     message = EmailMessage(subject,html_message,email_from,[recipient_email])
            #     message.content_subtype = 'html'
            #     message.send()
    if not created:
        subscribers=email_subscription.objects.all()
        email_from = settings.EMAIL_HOST_USER
        subject = instance.subject_email
        for subscriber in subscribers:
            recipient_email=subscriber.email
            if instance.offers!='0' and instance.offers_date is not None and instance.subject_email:
                context = {
                        'name':instance.course_name,
                        'Description':instance.Description,
                        'offers':instance.offers,
                         'date':instance.offers_date             
                    }
                html_version = 'email.html'
                html_message = render_to_string(html_version, {'context': context})
                message = EmailMessage(subject,html_message,email_from,[recipient_email])
                message.content_subtype = 'html'
                message.send()
                
                # else:
                #     context = {
                #     'name':instance.course_name,
                #     'Description':instance.Description,
                #     'offers':instance.offers
                #     }
                #     html_version = 'email.html'
                #     html_message = render_to_string(html_version, {'context': context})
                #     message = EmailMessage(subject,html_message,email_from,[recipient_email])
                #     message.content_subtype = 'html'
                #     message.send()
    



    

yogashala/forms.py
from enum import unique
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser
from django_countries.fields import CountryField    
from django_countries import widgets, countries
from django_countries.widgets import CountrySelectWidget
from django.dispatch import receiver
from .models import profile,blog
from django.db.models.signals import post_save



class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)
	nationality =forms.ChoiceField(widget=CountrySelectWidget,choices=countries)
	firstname=forms.CharField(required=True,max_length=200)
	lastname=forms.CharField(required=True,max_length=300)



	class Meta:
		model = User
		fields = ("username", "email",'firstname','lastname',"password1", "password2",'nationality')

class blogForm(forms.ModelForm):
	class Meta:
		model=blog
		fields='__all__'
		exclude=['username']

yogashala/templates/about-us.html
{% extends 'index.html' %}
{% block content %}
{% load static %}
<style>
    button, button::after {
  width: 380px;
  height: 86px;
  font-size: 36px;
  font-family: 'Bebas Neue', cursive;
  background: linear-gradient(45deg, #0134ff 5%);
  border: 0;
  letter-spacing: 3px;
  line-height: 88px;
  box-shadow: 6px 0px 0px #00E6F6;
  /* outline: transparent; */
  position: relative;
}


</style>
    <!-- About Section Begin -->
    <body>
    <section class="about spad">
        <div class="container">
            <div class="about__services">
                <div class="row">
                    <div class="col-lg-3 col-md-4 col-sm-6">
                        <div class="services__item">
                            <img src="{% static 'img/about/af-1.png' %}" alt="" class="rotate">
                            <h5>Full Blessing</h5>
                            <p>Embrace the Chance to Elevate Your puja Journey, Find Serenity, Renew Your Spirit, and Immerse in Vedic Beauty.</p>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-4 col-sm-6">
                        <div class="services__item">
                            <img src="{% static 'img/about/af-2.png' %}" alt="" class="rotate">
                            <h5>Peace and Purity</h5>
                            <p>Discover the Path to Purity and Inner Peace by Participating in Sacred Puja Rituals, a Journey of Spiritual Renewal.</p>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-4 col-sm-6">
                        <div class="services__item">
                            <img src="{% static 'img/services/services-4.png' %}" alt="" class="rotate">
                            <h5>Seeking Guidance
                            </h5>
                            <p>Discover Your Path with Our Exclusive Spiritual Services. Your Journey, Our Commitment.</p>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-4 col-sm-6">
                        <div class="services__item">
                            <img src="{% static 'img/services/services-2.png' %}" alt="" class="rotate">
                            <h5>Expressions of Devotion
                            </h5>
                            <p>It encapsulate heartfelt ways individuals connect with their faith, including prayer, ritual, art, and service to their divine.</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-7 p-0">
                    <div class="about__pic">
                        <img src="{% static 'img/about/fire.png' %}" alt="" style="margin-top:-80px;height:500px;margin-left:30px;">
                    </div>
                </div>
                <div class="col-lg-5 p-0">
                    <div class="about__text">
                        <div class="section-title">
                            <!-- <img src="{% static 'img/icon.png' %}" alt=""> -->
                            <h2>What We Do</h2>
                            <p>To be invited to your location to perform any kind puja services</p>
                        </div>
                        <div class="about__bar">
                            <div class="about__bar__item">
                                <p style="font-size: 30px;">&#128134;Customized Pujas</p>
                                <!-- <div id="bar1" class="barfiller">
                                    <span class="tip"></span>
                                    <span class="fill" data-percentage="82"></span>
                                </div> -->
                            </div>
                            <div class="about__bar__item">
                                <p style="font-size: 30px;">&#128073;Traditional Rituals</p>
                                <!-- <div id="bar2" class="barfiller">
                                    <span class="tip"></span>
                                    <span class="fill" data-percentage="73"></span>
                                </div> -->
                            </div>
                            <div class="about__bar__item">
                                <p style="font-size: 30px;">&#127764;Vedic Astrology</p>
                                <!-- <div id="bar3" class="barfiller">
                                    <span class="tip"></span>
                                    <span class="fill" data-percentage="82"></span>
                                </div> -->
                            </div>
                            <div class="about__bar__item">
                                <p style="font-size: 30px;">&#128329;Vastu Consultations</p>
                                <!-- <div id="bar4" class="barfiller">
                                    <span class="tip"></span>
                                    <span class="fill" data-percentage="86"></span>
                                </div> -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- About Section End -->

    <!-- Team Section Begin -->
    
    <!-- Team Section End -->

    <!-- Classes Section Begin -->
    <section class="upcoming-classes spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section-title normal-title text-center mb-4">
                        <h2>What We Offer</h2>
                        <p>Experience the richness of traditional Hindu rituals, personalized pujas, festival celebrations, and Vedic astrology guidance with [Company Name].</p>
                    </div>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-md-8 col-sm-10 text-center">
                    <button class="btn btn-primary btn-lg btn-block mb-3">
                        <a href="{% url 'courses' %}" class="text-white">Click to Book Puja</a>
                    </button>
                </div>
            </div>
        </div>
    </section>
    
        
        </body>
      {% endblock %}

yogashala/templates/booked.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
<style>
    .custom-card-image {
        width: 100%;
        height: 200px;
        object-fit: cover;
    }

    .card {
        border: none;
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
    }

    .card-title {
        font-size: 1.5rem;
    }

    .card-text {
        font-size: 1rem;
        color: #777;
    }

    /* .btn-custom {
    } */

    .btn-custom:hover {
        background-color: #d32f2f;
    }
</style>

<body>
    <header class="text-center py-5">
        <h3>Thank you for your booking! &#128522;</h3>
        <button class="btn btn-danger mt-3">Need Assistance</button>
        <p class="mt-4">Our team will contact you soon</p>
        <p>Check your email for confirmation &#128231;</p>
        <h3 class="mt-5">Explore More</h3>
    </header>

    <div class="container-fluid">
        <div class="row justify-content-center">
            <!-- Main Content -->
            <main class="col-md-9">
                <div class="row">
                    <!-- Loop through your Django objects -->
                    {% for i in course %}
                    <div class="col-md-4 mb-4">
                        <div class="card">
                            <img src="{{ i.file_mainpic.url }}" class="card-img-top custom-card-image" alt="{{ i.course_name }}">
                            <div class="card-body">
                                <h2 class="card-title">{{ i.course_name }}</h2>
                                <p class="card-text">{{ i.Description | truncatechars:150 }}</p>
                                <a href="{% url 'course_detail' pk=i.pk %}" class="btn btn-primary">BOOK NOW</a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    <!-- End loop -->
                </div>
            </main>
        </div>
    </div>
    <div class="text-center mt-4">
        <a href="{% url 'courses' %}" class="btn btn-primary btn-lg">Find More Puja</a>
    </div>
</body>
{% endblock %}

yogashala/templates/booking.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Pandit G - Services</title>
    <style>
        /* Reset default styles for better email compatibility */
        body, table, td, p {
            margin: 0;
            padding: 0;
        }

        table {
            border-collapse: collapse;
            border-spacing: 0;
        }

        /* Apply inline styles for email */
        .container {
            max-width: 600px;
            margin: 20px auto;
            padding: 20px;
            background-color: #f8f9fa;
            font-family: Arial, sans-serif;
        }

        .card {
            border: 1px solid #e9ecef;
            box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1);
            border-radius: 5px;
            overflow: hidden;
        }

        .card-header {
            background-color: #f8f9fa;
            text-align: center;
            padding: 10px;
        }

        .card-title {
            display: flex;
            justify-content: space-between;
            align-items: center;
            color: black;
            font-size: 20px;
            padding: 10px;
        }

        .card-title div {
            flex: 1;
            text-align: center;
        }

        .card-title .left {
            text-align: left;
        }

        .card-title .right {
            text-align: right;
        }

        .card-body {
            background-color: white;
            padding: 20px;
        }

        .column {
            margin-top: -10px;
            padding: 10px;
            border-top: 1px solid #e9ecef;
            font-size: 16px;
        }

        p {
            text-align: center;
        }

        /* Footer styles */
        .footer {
            background-color: #f8f9fa;
            padding: 10px;
            text-align: center;
        }

        .footer p {
            font-size: 14px;
        }

    </style>
</head>
<body>
    <div class="container">
        <div class="card">
            <div class="card-header">
                <h2>Billing Invoice</h2>
                <h3>Pandit G</h3>
                <p>"At your services"</p>
                <p>Available in USA, Australia, Nepal, India, Canada</p>
            </div>
            <div class="card-title">
                <div class="left">#REF: {{context.id}}</div>
            </div>
            <div class="card-body">
                <div class="column">
                    <p><strong>Purchase_date:</strong> {{ context.date }}</p>
                </div>
                <div class="column">
                    <p><strong>Puja:</strong> {{ context.puja_name }}</p>
                </div>
                <div class="column">
                    <p><strong>Price:</strong> {{ context.price }} USD</p>
                </div>
                <div class="column">
                    <p><strong>Payment:</strong> {{ context.payment }}</p>
                </div>
                <div class="column">
                    <p><strong>Address:</strong> {{ context.address }}</p>
                </div>
            </div>
        </div>

        <!-- Footer -->
        <div class="footer">
            <p><strong>Company Details:</strong> Pandit G Company, Address: Anamnagar, Kathmandu, Phone: +9779869111406</p>
        </div>
    </div>
</body>
</html>

yogashala/templates/course_purchase_cart.html
{% extends 'index.html' %}
{% load static %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <!-- Display Cart Items -->
        <div class="col-md-6" style="margin-top: 25px;">
            <div class="card billing-container shadow-lg">
                <div class="card-body">
                    {% for item in carts %}
                        <div class="row billing-item mb-4 p-4 bg-light rounded">
                            <div class="col-md-5 billing-item-details">
                                <h5 class="card-title text-primary">{{ item.name }}</h5>
                                <img src="{{ item.img }}" class="img-fluid" style="width: 85px; height: 65px;" alt="{{ item.name }}">
                            </div>
                            <div class="col-md-3 billing-item-quantity">
                                <div class="text-muted">Required</div>
                                <div>{{ item.count }}</div>
                            </div>
                            <div class="col-md-2 billing-item-price">
                                <p class="text-success font-weight-bold">Price: {{ item.price }}</p>
                            </div>
                            <div class="col-md-2 billing-item-price">
                                <a href="{% url 'remove_from_cart' product_id=item.id %}" class="text-muted ms-2"><i class="fa fa-trash fa-2x"></i></a>
                            </div>

                        </div>
                    {% endfor %}
                    <p>Total cost: {{ total_p }}</p>
                </div>
            </div>
        </div>

        <!-- Additional Styling for Purchase Form Section -->
        <div class="col-md-6">
            <div class="card mt-4 billing-container shadow-lg">
                <div class="card-body">
                    <h2 class="mb-4 text-primary">Purchase Form</h2>
                    <form method="post" action="{% url 'course_purchase_cart' %}">
                        {% csrf_token %}
                        <!-- Basic customer information -->
                        <div class="form-group">
                            <label for="id_name" class="text-primary">Name:</label>
                            <input type="text" name="name" class="form-control" required>
                        </div>
                        <div class="form-group">
                            <label for="id_country" class="text-primary">Country:</label>
                            <input type="text" name="country" class="form-control" required>
                        </div>
                        <div class="form-group">
                            <label for="id_location" class="text-primary">Location:</label>
                            <input type="text" name="location" class="form-control" required>
                        </div>
                        <div class="form-group">
                            <label for="id_email" class="text-primary">Email:</label>
                            <input type="email" name="email" class="form-control" required>
                        </div>
                        <!-- Additional customer details -->
                        <div class="form-group">
                            <label for="id_contact" class="text-primary">Contact:</label>
                            <input type="text" name="contact" class="form-control" required>
                        </div>
                        <div class="form-group">
                            <label for="id_any_special_request" class="text-primary">Any Special Request:</label>
                            <textarea name="any_special_request" class="form-control"></textarea>
                        </div>

                        <div class="form-group">
                            <label class="text-primary">Payment Options:</label>
                            <div class="form-check">
                                <input type="radio" id="esewa" name="payment_option" value="esewa" class="form-check-input" required>
                                <label for="esewa" class="form-check-label">eSewa</label>
                            </div>
                            <div class="form-check">
                                <input type="radio" id="international" name="payment_option" value="international" class="form-check-input" required>
                                <label for="international" class="form-check-label">card</label>
                            </div>
                            <div class="form-check">
                                <input type="radio" id="international" name="payment_option" value="cod" class="form-check-input" required>
                                <label for="cod" class="form-check-label">payment on puja</label>
                            </div>
                            <!-- Add more payment options as needed -->
                        </div>
        



                        
                        <!-- Courses selection -->
                        <!-- <div class="form-group text-center">
                            <label for="id_items" class="text-primary">Select Courses:</label>
                            <ul class="list-group d-inline-block">
                                {% for course in carts %}
                                    <li class="list-group-item">{{ course.name }}</li>
                                {% endfor %}
                            </ul>
                        </div> -->
                        <button type="submit" class="btn btn-primary btn-lg">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

yogashala/templates/esewapayment.html
<html>
<body>
    <h3 style="text-align:center;">you will be redirected to esewa website ..</h3>
    <form action="https://uat.esewa.com.np/epay/main" method="POST" id="myform">
    <input value="{{ t }}" name="tAmt" type="hidden">
    <input value="{{ t }}" name="amt" type="hidden">
    <input value="0" name="txAmt" type="hidden">
    <input value="0" name="psc" type="hidden">
    <input value="0" name="pdc" type="hidden">
    <input value="epay_payment" name="scd" type="hidden">
    <input value="ee2c3ca1-696b-4cc5-a6be-2c40d929d453" name="pid" type="hidden">
    <input value="http://127.0.0.1:8000/" type="hidden" name="su">
    <input value="{{request.build_absolute_uri}}" type="hidden" name="fu">
    <input value="Submit" type="submit">

    </form>
    <script>
        setTimeout(function(){
        document.getElementById("myform").submit()
        },500)
    </script>
</body>
</html>

yogashala/templates/login.html
{% extends 'index.html' %}
{% block content %}
{% load crispy_forms_tags %} 

    <h1 style="margin-left:600px;">User Login</h1>
    <form method="POST" >
         {% csrf_token %}
         <div style="width:300px;margin-left:630px;margin-top:50px;margin-bottom:50px;">
        {{form|crispy}}
        
        <button>Login</button>



    </div>
    </form>

    <a href="/reset_password/" style="margin-left:20px;">forgot reset_password?</a>

    {% endblock %}

yogashala/templates/main.html
<a href="https://colorlib.com/wp/templates/"><img src="https://colorlib.com/wp/wp-content/uploads/sites/2/colorlib-push-logo.png" alt="Colorlib logo"></a>
<h1 style="text-align:center;">Thank you for using our template!</h1>
<p style="text-align:center;">For more awesome templates please visit <strong><a href="https://colorlib.com/wp/templates/">Colorlib</a></strong>.</p>
<br>
<p style="text-align:center; color:red;"><strong>Copyright information for the template can't be altered/removed unless you purchase a license.</strong>

<p style="text-align:center;"><strong>Removing copyright information without the license will result in suspension of your hosting and/or domain name(s).</strong>

<p style="text-align:center;"><strong>More information about the license is available <a href="https://colorlib.com/wp/licence/">here</a></strong>.</p>

<style>
img {
  margin: 0 auto;
  display: block;
  margin-top: 20%;
}
</style>